### ISSUE TITLE
TODO: support yarl.URL()

### ISSUE THREAD

**Issue by webknjaz** [pengutronix/aiohttp-json-rpc#18]
This is essential URL data structure used by aiohttp (and invented alongside with it), so all of the machinery of current package should support it (and probably use internally).
This may be addressed via #17 or separate PR.

**Comment by webknjaz** [comment]
Ref: https://github.com/aio-libs/aiohttp/issues/2481#issuecomment-342832017

**Comment by fscherf** [comment]
Ack! The client is the only place we handle urls so i think it's ok to add this changes to #17.
