### ISSUE TITLE
Expose aiohttp application to rpc function

### ISSUE THREAD

**Issue by webknjaz** [pengutronix/aiohttp-json-rpc#20]
I've noticed (supposingly) a design issue with RPC handlers.

I've got an app, where I attach some interfaces to globally accessible app object. I need to access app from within the handler therefore.
But I get only `request` as an input and that's it.
I guess, it is possible to retrieve app via `request.http_request.app`, but that's too verbose and annoying to repeat over and over in every each handler. Also using `@unpack_request_args` hides access to `request` at all.

Currently I'm thinking about introducing some kind of Class-Based "views" concept.

@fscherf do you have any additional ideas regarding this?

**Comment by fscherf** [comment]
Interesting! Like in Django? How would a class based view reach the app?

**Comment by webknjaz** [comment]
I'd say more like in aiohttp itself. I'd put it into `self.app`

**Comment by fscherf** [comment]
Ah ok. Can you mock-up how the api should look like?

**Comment by webknjaz** [comment]
We'll, my mock-up turned out to be a combo of multiple approaches (cherrypy + aiohttp/django CBV)

```python
from aiohttp_json_rpc import JsonRpcView, expose

class SomeRpcView(JsonRpcView):
    @expose
    async def some_rpc_handler():
        self.request  # retrieves aiohttp request
        self.rpc_request  # retrieves json rpc req
        self.app  # retrieves aiohttp app
        # blah-blah

    @expose(as='other_name')  # makes RPC method accessible under `other_name` name
    async def some_other_rpc_handler():
        # blah-blah

# register that as usual aiohttp view
app = Application()
app.router.add_route('*', '/', SomeRpcView)
```

**Comment by webknjaz** [comment]
@fscherf any comments?

**Comment by webknjaz** [comment]
@fscherf so what do you think about such API?

**Comment by fscherf** [comment]
Hmm i think it's too much new complexity for such a simlpe approach.
```request.http_request.app``` isn't that bad and much simpler to implement, maintain and use in application code.

**Comment by webknjaz** [comment]
I cannot agree with the need of having tons of copy-paste across handlers

**Comment by fscherf** [comment]
what about something like this:

```python
class Foo:                        
    def __init__(self, app):      
        self.app = app
 
    @unpack_request_args
    async def foo(self, arg1, arg2, arg3):
        return str(self.app['conf'])

app = web.Application()
f = Foo(app)
rpc = JsonRpc()

rpc.add_methods(
   ('', f),
)
```

You would have access to your app, can use `unpack_request_args` and have something like a class based view. And it works out of the box without new code

**Comment by webknjaz** [comment]
Makes sense, let me think about it.

**Comment by fscherf** [comment]
@webknjaz did you come to a opinion?

**Comment by webknjaz** [comment]
Honestly, I didn't try it, but looks good. Let's close this case for now. Will update it once my colleagues @ZhukovGreen or @ahlinc try it out.

**Comment by ZhukovGreen** [comment]
@fscherf Hi Florian, we have a little problem here. Once there are class-based views, then, except a RpcRequest obj, we have a class instance being dispatched to the `rpc_method_wrapper` (decorator on the very end of the rpc.py).

**Comment by webknjaz** [comment]
So this basically means the need for decorator to support decorating methods/classes. Which needs PR.
