### ISSUE TITLE
Update to aiohttp v.3.0.1

### ISSUE THREAD

**Issue by ZhukovGreen** [pengutronix/aiohttp-json-rpc#21]
Hello, thank you for your package. Do you have some particular problems with the latest aiohttp?

**Comment by fscherf** [comment]
You are welcome :)
No particular problems :) i am working on the port right now

**Comment by ZhukovGreen** [comment]
cool, thanks @fscherf

**Comment by fscherf** [comment]
@ZhukovGreen v0.9 is there :) have fun und please report if you see problems

**Comment by ZhukovGreen** [comment]
@fscherf sure. Thx
