### ISSUE TITLE
Can't use an alternate 'loop' and client seems to constrained to web-sockets only

### ISSUE THREAD

**Issue by gschmottlach-xse** [pengutronix/aiohttp-json-rpc#23]
Please correct me if I'm wrong, but it doesn't appear possible to pass in (and use) an alternate *loop* other than the one returned by ```asyncio.get_event_loop()```. It seems that ```JsonRpcClient.connect()``` and ```JsonRpcClient.connect_url()``` would need to accept a ```loop``` keyword parameter so that this could be passed to the ```aiohttp.ClientSession()``` constructor. Since that's not possible it appears only the default one will be chosen for the JSON-RPC client. Would it be possible to add this additional keyword parameter so an outside loop can be substituted?

Finally, just to confirm, it appears this library **only** supports JSON-RPC over websockets and not HTTP. Is this a correct assumption? If so, is this something (HTTP support) that could easily be added?

Thanks . . .

**Comment by fscherf** [comment]
Hi @gschmottlach-xse,

# JsonRpcClient loop

No you perfectly right, `JsonRpcClient` does not support other loops than the standard loop in `aiohttp.ClientSession()` (yet). 

I think the best place for this is `JsonRpcClient.__init__`.

```python
class JsonRpcClient:
    def __init__(self, loop=none, [...]):
        self._loop = loop or asyncio.get_event_loop()

    def connect_url(self, url):
        with aiohttp.ClientSession(loop=self._loop, [...]) as session:
            [...]
```

As in your previous issue: Feel free to send patches or wait for me a few days, i'll inform you when the feature is released.

# HTTP methods
Yes you are right, at the moment only websockets are supported, no POST or GET

`rpc.py:120`
```python
@asyncio.coroutine                                                    
def __call__(self, request):                                          
    # prepare request                                                 
    request.rpc = self                                                
    self.auth_backend.prepare_request(request)                        
                                                                      
    # handle request                                                  
    if request.method == 'GET':                                       
                                                                      
        # handle Websocket                                            
        if request.headers.get('upgrade', '').lower() == 'websocket': 
            return (yield from self.handle_websocket_request(request))
                                                                      
        # handle GET                                                  
        else:                                                         
            return aiohttp.web.Response(status=405)                   
                                                                      
    # handle POST                                                     
    elif request.method == 'POST':                                    
        return aiohttp.web.Response(status=405)                       
```
You see: the code is prepared to get the methods `handle_post_request()` and `handle_get_request()`
but to implement this will take me a bit longer. But it`s planed!

**Comment by gschmottlach-xse** [comment]
Sounds like you have a handle on these issues as well. I wasn't sure what your roadmap might be but it appears you have plans to address these topics. As I mentioned in Issue #24 I'm patient for your updates and would be interested in trying them when they come available.

Thanks for making this module freely available . . .

**Comment by fscherf** [comment]
Sorry it took me so long. Much work, was sick two times, and it was a bit more complicated than i thougt.
I pushed the changes and i'll make a release very soon.

**Comment by gschmottlach-xse** [comment]
Understood . . . work and life have a way of interfering with the best of intentions. I was just thinking about these (pending) requests this morning. Glad to see that you've begun to address them. I think they'll really improve the robustness of your module.

Thanks for making progress . . .

**Comment by fscherf** [comment]
@gschmottlach-xse: You are absolutly right! And i am very thankful for anyone who helps me to test all kinds of use-cases and communication with third-party json-rpc implementations.

**Comment by fscherf** [comment]
Your feature request is implemented in v0.10

**Comment by gschmottlach-xse** [comment]
A hearty "thank-you" for your fixes for issues #23, #24, and #25. I (as well as others) appreciate your continued effort to support this module.

**Comment by fscherf** [comment]
@gschmottlach-xse you are welcome :) may i close your issues?

**Comment by gschmottlach-xse** [comment]
Yes, thanks again.
