### ISSUE TITLE
aiohttp 3.5

### ISSUE THREAD

**Issue by leenr** [pengutronix/aiohttp-json-rpc#38]
In [`setup.py`](https://github.com/pengutronix/aiohttp-json-rpc/blob/a6e8b57/setup.py#L12) _aiohttp_ version is currently limited by `<3.5`.

_aiohttp_ 3.5 was [released](https://github.com/aio-libs/aiohttp/releases/tag/v3.5.0) in the late December. Do you have plans to support it?

**Comment by fscherf** [comment]
Hi @leenr,

No i had no plans to support aiohttp 3.5, but @Tobotimus had :D
Anyway: Thanks for using and testing this project :)
