### ISSUE TITLE
Getting 'Invalid response status' on all calls

### ISSUE THREAD

**Issue by retke** [pengutronix/aiohttp-json-rpc#42]
I'm trying to use the lib and I pasted the server and client examples:

`rpc_server.py`
```py
from aiohttp.web import Application, run_app
from aiohttp_json_rpc import JsonRpc
import asyncio


async def ping(request):
    return 'pong'


if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    rpc = JsonRpc()
    rpc.add_methods(
        ('', ping),
    )

    app = Application(loop=loop)
    app.router.add_route('*', '/', rpc.handle_request)

    run_app(app, host='0.0.0.0', port=8080)
```
`rpc_client.py`
```py
import asyncio
from aiohttp_json_rpc import JsonRpcClient


async def ping_json_rpc():
    """Connect to ws://localhost:8080/rpc, call ping() and disconnect."""
    rpc_client = JsonRpcClient()
    try:
        await rpc_client.connect('localhost', 8080, '/rpc')
        call_result = await rpc_client.call('ping')
        print(call_result)  # prints 'pong' (if that's return val of ping)
    finally:
        await rpc_client.disconnect()


asyncio.get_event_loop().run_until_complete(ping_json_rpc())
```

When I execute `rpc_client.py`, I get the following error:
```py
Traceback (most recent call last):
  File "rpc_client.py", line 9, in ping_json_rpc
    await rpc_client.connect('localhost', 8080, '/rpc')
  File "/usr/local/lib/python3.7/site-packages/aiohttp_json_rpc/client.py", line 136, in connect
    await self.connect_url(url, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/aiohttp_json_rpc/client.py", line 125, in connect_url
    self._ws = await self._session.ws_connect(url)
  File "/Users/laggron/Library/Python/3.7/lib/python/site-packages/aiohttp/client.py", line 615, in _ws_connect
    headers=resp.headers)
aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rpc_client.py", line 16, in <module>
    asyncio.get_event_loop().run_until_complete(ping_json_rpc())
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "rpc_client.py", line 13, in ping_json_rpc
    await rpc_client.disconnect()
  File "/usr/local/lib/python3.7/site-packages/aiohttp_json_rpc/client.py", line 152, in disconnect
    await self._ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
```
The server *is* running, because I get `Cannot connect to host localhost:8080` when the server is off.
I tried calling the ping method with `curl` to see if the problem was from the client or the server, and this is what I got
```bash
$ curl -v -H "content-type: application/json-rpc" --data '{"jsonrpc": "2.0", "method": "ping", "params": {}, id: 0}' http://0.0.0.0:8080
* Rebuilt URL to: http://0.0.0.0:8080/
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 8080 (#0)
> POST / HTTP/1.1
> Host: 0.0.0.0:8080
> User-Agent: curl/7.54.0
> Accept: */*
> content-type: application/json-rpc
> Content-Length: 55
>
* upload completely sent off: 55 out of 55 bytes
< HTTP/1.1 405 Method Not Allowed
< Content-Length: 0
< Content-Type: application/octet-stream
< Date: Thu, 14 Feb 2019 13:15:35 GMT
< Server: Python/3.7 aiohttp/3.4.4
<
* Connection #0 to host 0.0.0.0 left intact
```
This time, I get `405 Method Not Allowed`, so the problem is from the server. I don't get what's wrong with what I'm doing...

**Comment by fscherf** [comment]
hi @retke,

i am sorry it took me so long.
First of all: Thanks for your interest and reporting problems.

I didn't test your code but the first thing i see is that the server defines the url `/` for the rpc but the client tries to connect to `/rpc`.


Testing websockets using curl may work, but not like you do because if i read your command line correctly your curl tries a simple GET request with the header `CONTENT-TYPE` set.
The rpc don't care about the content type, it looks for `UPGRADE` to start a websocket connection and that is currently the only way to communicate with the rpc. Neither POST or GET are implemented.

[for more details]
https://github.com/pengutronix/aiohttp-json-rpc/blob/2364bf3ae8d3e57dc0e7dde0d7588d55f46a18ff/aiohttp_json_rpc/rpc.py#L253

For debbuging sessions i would recomment tools like this:
https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=en

**Comment by retke** [comment]
Thanks a lot for your answer, removing `/rpc` fixed the problem! I created a quick pull request to fix this, since I pasted the example from the README.
The debug tool you suggested is really useful *(I found it for Firefox too)*, thanks for this too!

The issue is resolved, I'm closing this, but there's one last thing I'd like to ask without opening a new issue: how can I create a function that gets triggered when any request is received (what `handle_request` does)? I would love to have this handler to log the incoming events myself, which would be useful for debugging.

**Comment by fscherf** [comment]
@retke i am sorry, there is no hook for custom code, but if you increase the log level you get debug information. In this example the log level is set to debug:

```
In [1]: call('ping')
DEBUG:aiohttp-json-rpc.client:#0: > {"id": 0, "method": "ping", "jsonrpc": "2.0"}
DEBUG:aiohttp-json-rpc.server:raw msg received: {"id": 0, "method": "ping", "jsonrpc": "2.0"}
DEBUG:aiohttp-json-rpc.server:waiting for messages
DEBUG:aiohttp-json-rpc.server:message decoded: JsonRpcMsg(type=10, data={'id': 0, 'method': 'ping', 'params': None, 'jsonrpc': '2.0'})
DEBUG:aiohttp-json-rpc.server:msg gets handled as request
DEBUG:aiohttp-json-rpc.client:#0: < {"id": 0, "result": "pong", "jsonrpc": "2.0"}
DEBUG:aiohttp-json-rpc.client:#0: waiting for messages
Out[1]: 'pong'
```
