### ISSUE TITLE
Cannot handle more than one positional argument

### ISSUE THREAD

**Issue by retke** [pengutronix/aiohttp-json-rpc#44]
So, I was happy to have the RPC working on my code, so I tested more complex things and I broke the lib *again*.

I have the following method:
```py
async def connect(self, token: str, name: str):
    # do random things...
    return "some text"
```
Notice it has two arguments.

When I try to call it with the websockets debug tool, I'm getting the following error (debug enabled):
```
DEBUG:aiohttp-json-rpc.server:raw msg received: {"jsonrpc": "2.0", "id": 0, "method": "MINECRAFTSRV__CONNECT", "params": ["hello", "world"]}
DEBUG:aiohttp-json-rpc.server:waiting for messages
DEBUG:aiohttp-json-rpc.server:message decoded: JsonRpcMsg(type=10, data={'jsonrpc': '2.0', 'id': 0, 'method': 'MINECRAFTSRV__CONNECT', 'params': ['hello', 'world']})
DEBUG:aiohttp-json-rpc.server:msg gets handled as request
ERROR:root:connect() missing 2 required positional arguments: 'token' and 'name'
Traceback (most recent call last):
  File "/Users/laggron/Library/Python/3.7/lib/python/site-packages/aiohttp_json_rpc/rpc.py", line 316, in _handle_rpc_msg
    msg=msg,
  File "/Users/laggron/Library/Python/3.7/lib/python/site-packages/aiohttp_json_rpc/rpc.py", line 146, in __call__
    return await self.method(**method_params)
TypeError: connect() missing 2 required positional arguments: 'token' and 'name'
```
Looks like the code isn't giving the arguments, so I searched a bit inside the source code and found where the arguments were processed. I launched the program with the Visual Studio Code debugger tool and added some breakpoints in `JsonRpcMethod.__call__`.

I noticed the following problem: `self.required_args` is equal to `[]`, it didn't find the positional arguments. When I edit this value to `["token", "name"]`, everything works.

So the problem must come from this part:
```py
# required args
self.required_args = copy(self.args)

if not (len(self.args) == 1 and self.defaults is None):
    self.required_args = [
        i for i in self.args[:-len(self.defaults or ())]
        if i not in self.CREDENTIAL_KEYS
    ]
```
I tried fixing this part of code to make a PR, but I just can't understand how it works. Like, you're getting the lenght of a boolean?? The `or` statement from `len(self.defaults or ())` always return `True` or `False`, this is probably the problem, but I don't know how to fix that and what you wanted it to do... So I'm posting this issue, I tried but I can't fix this myself, I hope my research can be useful to fix the problem.

**Comment by retke** [comment]
A friend found a fix to the issue, just opened a PR to fix the issue. Dunno if it's the best solution, but that's the only thing we found.

**Comment by fscherf** [comment]
hi @retke,

last night i was able to reproduce this. It seems this time you really found something. I will do some debugging myself and reviewing your pull request. Thanks for reporting!

Addressing you confusion about this call:
```python
self.args[:-len(self.defaults or ())]
```
The `or` statement returns nerver a boolean `False` in this case:

[IPython output]
```python
In [2]: defaults = ()

In [3]: defaults or ()
Out[3]: ()

In [4]: defaults = False

In [5]: defaults or ()
Out[5]: ()

In [6]: len(defaults or ())
Out[6]: 0
```

**Comment by fscherf** [comment]
hi @retke,

I reviewed and pushed your fix. Thanks for contributing :)

**Comment by retke** [comment]
Thank you!
