### ISSUE TITLE
PasswdAuthBackend: AttributeError: 'function' object has no attribute 'method'

### ISSUE THREAD

**Issue by DMT07** [pengutronix/aiohttp-json-rpc#57]
When implementing the PasswdAuthBackend from passwd_example.py exactly from the example, I get the following error when calling one of the auth_backend methods, such as login() from a client connection:

```
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<JsonRpc._handle_rpc_msg() done, defined at c:\users\tomlindm\appdata\local\programs\python\python38-32\lib\
site-packages\aiohttp_json_rpc\rpc.py:280> exception=AttributeError("'function' object has no attribute 'method'")>
Traceback (most recent call last):
  File "c:\users\tomlindm\appdata\local\programs\python\python38-32\lib\site-packages\aiohttp_json_rpc\rpc.py", line 307, in _handle_rpc_msg
    http_request.methods[msg.data['method']].method,
AttributeError: 'function' object has no attribute 'method'
```

The ping() method that is added to the rpc host works fine, but the methods instantiated in PasswdAuthBackend fails with the above error.

**Comment by fscherf** [comment]
Hi @DMT07,

you are right, i can reproduce your problem on master.
I will release a fix as soon as i can.

**Comment by DMT07** [comment]
So the problem seems to be in line 139 in aiohttp_json_rpc/auth/passwd.py

The methods should be JsonRpcMethod() objects which it is not.

`method_pool = dict(
            login=self.login,
            logout=self.logout,
            create_user=self.create_user,
            delete_user=self.delete_user,
            set_password=self.set_password,
            **request.rpc.methods
        )`

Adding JsonRpcMethod to fix the problem:
`from aiohttp_json_rpc.rpc import JsonRpcMethod`
and
`method_pool = dict(
            login=JsonRpcMethod(self.login),
            logout=JsonRpcMethod(self.logout),
            create_user=JsonRpcMethod(self.create_user),
            delete_user=JsonRpcMethod(self.delete_user),
            set_password=JsonRpcMethod(self.set_password),
            **request.rpc.methods
        )`

**Comment by fscherf** [comment]
@DMT07 

Yes you are right. I did exactly that, and fixed an additional bug in ``set_password()``.
Both patches are included in ``v0.13.2``

**Comment by fscherf** [comment]
@DMT07 
did this fix your problem?

**Comment by DMT07** [comment]
It did, thank you.
