### ISSUE TITLE
concurrent.futures._base.TimeoutError occuring Randomly 

### ISSUE THREAD

**Issue by Noor-Kalibbala** [pengutronix/aiohttp-json-rpc#61]
the code below some times ti cause timeoutError randomly
```python
if timeout:
        await asyncio.wait_for(self._pending[id], timeout=timeout)
```
the error is 
concurrent.futures._base.TimeoutError

**Comment by fscherf** [comment]
I don't think its random. asyncio.wait_for should raise a TimeoutError when the given awaitable does not gets set in time.

**Comment by Noor-Kalibbala** [comment]
@fscherf  in source code  of this repository if timeout argument is not given, the default value is used which is None, source I don't know why asyncio_wait for raises this error when Timeout argument is None

**Comment by fscherf** [comment]
@Noor-Kalibbala 
But if `timeout` is not set `asyncio.wait_for()` should not be called in the first place, if i read the snipped correctly

**Comment by Noor-Kalibbala** [comment]
@fscherf  That snippet is within the source code of the code , so i don't know what the developer was intending to do in first place

**Comment by Noor-Kalibbala** [comment]
@fscherf  that snippet is found in aiohttp_json_rpc/client.py module

**Comment by fscherf** [comment]
@Noor-Kalibbala Ah! We are talking abaut https://github.com/pengutronix/aiohttp-json-rpc/blob/master/aiohttp_json_rpc/client.py#L160

Okay! I assume your timeout problems are not random but happen if your call runs longer than 1s, because that's the default timeout. If you don't want your call to timeout try something like this:

```python
client.call('my-method', timeout=None)
```

**Comment by Noor-Kalibbala** [comment]
@fscherf  Ohhhh yah i think the problem emanates from that because some of my functions are heavy. Thanks very much for your response, i will give it a shot

**Comment by fscherf** [comment]
@Noor-Kalibbala you are welcome :)
Can i close this issue?

**Comment by Noor-Kalibbala** [comment]
@fscherf okay let me close it, thanks
