### ISSUE TITLE
Automate package release to PYPI process

### ISSUE THREAD

**Issue by webknjaz** [pengutronix/aiohttp-json-rpc#9]
So, there's `setuptools_scm` package making use of git tags for determining the version of distribution package + there's a deployment provider in Travis CI helping to publish package to PYPI.

@fscherf would you accept PR implementing above? The result be the following: to release new version of dist to PYPI you'd have to push a new tag to github and everything else is done automatically.

**Comment by fscherf** [comment]
@webknjaz nice idea but i think it's a little bit over kill for my "release process" because all i have to do atm is create a release tag and run "./setup.py sdist upload" and i am pretty happy with that because this is code i write for my company and it runs *very* critical infrastructure and i want to have full controll over the development and relaese process.

btw: I had some trouble to get my test suite to run on travis. I didn't invest very much time on this problem because i use my company's jenkins server for ci and there it works.

**Comment by webknjaz** [comment]
I think I could fix Travis and bits of packaging since we'll likely continue using it.

Btw, could you plz also upload wheels?

P.S. `twine` is the new official way of building and uploading distributions

**Comment by webknjaz** [comment]
P.P.S. `setuptools_scm` has this mode when it generates `version.py` (or whatever you call it) when you run `setup.py sdist` (or so), this way you'd not need to make additional commit editing version string in `setup.py`, but you'd would still have version in python code.

**Comment by webknjaz** [comment]
Wow, the fix is pretty easy: you try running non-installed versions of python in travis job.

**Comment by fscherf** [comment]
Thanks for your travis patches, i review them atm but i don't see any reason to not merge them (or most of them).

I don't use twine at the moment but you are right, the official pypi tool recommendations page recommends twine too, so i will take a look at it.

I am still not sure if i want auto-magic in the deployment process. And giving my login credentials to travis.ci (to be fair: encrypted, but hmmmmmm...) does'nt seem right to me while the relaeses are very simple to do and don't happen so often

**Comment by webknjaz** [comment]
I see, still if you have lots of packages to maintain you'll eventually start thinking of automation since you don't always want to even do smth locally, but cut a release from github directly :)

**Comment by fscherf** [comment]
Yes you are absolutly right but atm i maintain like 5 packages for my company with 2 releases in a month tops :) thats totally manageable and it's on company time :D 
Also we depend with critical infrastructure on a stable release process, so if it is that simple to do it on my own i dont want fancy tools which are not fully under my control.

You mentioned you want me to do upload wheels. If you want you can add a Makefile with a release stage which runs all {twine,./setup.py} calls you want me to run on release days.

**Comment by webknjaz** [comment]
I'd add smth like alias `release = bdist_wheel sdist upload` to `setup.cfg`, but yes, Makefile might be better

**Comment by webknjaz** [comment]
Now you should be able to run `make release-to-pypi` or `make dist` wrapping some of your routines.

**Comment by fscherf** [comment]
FTR: @webknjaz added a Makefile to his current PR.
Can i close this issue?
